language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install:
  - |
    if [[ ${RUBY_VERSION} =~ ^ruby-2.3 ]]; then
      gem uninstall -i /home/travis/.rvm/gems/${RUBY_VERSION}@global bundler -x
    fi
  - gem install bundler -v 1.17.3
script: "bundle exec rake spec"
addons:
  code_climate:
    repo_token: 155202524386dfebe0c3267a5c868b5417ff4cc2cde8ed301fb36b177d46a458
